dumper:
  worker:
    limit: 2
    workMode: milvus1x

    reader:
      bufferSize: 1024

    writer:
      bufferSize: 1024

loader:
  worker:
    limit: 2

source:
  mode: local

  local:
    meta:
      mode: mock
      mockFile: ./testfiles/milvus1x/test1w/meta.json
    tablesDir: ./testfiles/milvus1x/test1w/tables

target:
  mode: remote

  remote:
    outputDir: testfiles/output/

    cloud: aws
    endpoint: 0.0.0.0:9000
    region: ap-southeast-1
    bucket: a-bucket
    ak: minioadmin
    sk: minioadmin
    useIAM: false
    useSSL: false
    checkBucket: true

  milvus2x:
    endpoint: localhost:19530
    username: xxxxx
    password: xxxxx