dumper:
  worker:
    limit: 2
    workMode: faiss

    reader:
      bufferSize: 1024

    writer:
      bufferSize: 1024

loader:
  worker:
    limit: 2

source:
  mode: local

  local:
    faissFile: ./testfiles/faiss/faiss_ivf_flat.index

target:

  create:
    collection:
      name: test1w
      shardsNums: 2
      dim: 256
      metricType: L2


  mode: remote

  remote:
    outputDir: testfiles/output/

    cloud: aws
    endpoint: 0.0.0.0:9000
    region: ap-southeast-1
    bucket: a-bucket
    ak: minioadmin
    sk: minioadmin
    useIAM: false
    useSSL: false
    checkBucket: true

  milvus2x:
    endpoint: localhost:19530
    username: xxxxx
    password: xxxxx